// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.15.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class CalcReturnForDart {
  final Float64List result;
  final List<Constant> constants;

  const CalcReturnForDart({
    required this.result,
    required this.constants,
  });

  @override
  int get hashCode => result.hashCode ^ constants.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CalcReturnForDart &&
          runtimeType == other.runtimeType &&
          result == other.result &&
          constants == other.constants;
}

class Constant {
  final String identity;
  double value;
  final double max;
  final double min;
  final double step;

  Constant({
    required this.identity,
    required this.value,
    required this.max,
    required this.min,
    required this.step,
  });

  @override
  int get hashCode =>
      identity.hashCode ^
      value.hashCode ^
      max.hashCode ^
      min.hashCode ^
      step.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Constant &&
          runtimeType == other.runtimeType &&
          identity == other.identity &&
          value == other.value &&
          max == other.max &&
          min == other.min &&
          step == other.step;
}

class VariableBuilder {
  final String identity;
  final bool uninitialized;
  final double min;
  final double max;
  final double step;
  final double value;

  const VariableBuilder({
    required this.identity,
    required this.uninitialized,
    required this.min,
    required this.max,
    required this.step,
    required this.value,
  });

  @override
  int get hashCode =>
      identity.hashCode ^
      uninitialized.hashCode ^
      min.hashCode ^
      max.hashCode ^
      step.hashCode ^
      value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VariableBuilder &&
          runtimeType == other.runtimeType &&
          identity == other.identity &&
          uninitialized == other.uninitialized &&
          min == other.min &&
          max == other.max &&
          step == other.step &&
          value == other.value;
}
